name: "Zap"

on:
  workflow_dispatch:
  push:

jobs:
  dastardly:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: get-ip
        run: |
          HOST=`ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'`
          echo "HOST=$HOST" >> $GITHUB_OUTPUT

      - run: |
          cd apps/gql-api
          yarn
          node index.js &


      - run: |
          docker run -i -v $PWD:/zap/wrk -e TARGET_URL=http://${{steps.get-ip.outputs.HOST}}:3001/ --entrypoint bash owasp/zap2docker-stable -c '/zap/zap-api-scan.py -t "$TARGET_URL" -f "graphql" -J report.json'

          cat report.json

      - name: dast/nuclei
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          TARGET_URL: "http://${{steps.get-ip.outputs.HOST}}:3001/graphql"
          API_FORMAT: graphql
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          api_endpoint: https://api.dev.boostsec.io
          registry_module: dast/zap
          additional_args: --registry . --offline
          log_level: DEBUG

